
name: 头条热点推送

on:
  schedule:
    # 设置启动时间，为 UTC 时间, UTC23点 对应北京时间早8点
    - cron : '0 1 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Toutiao Task
      run: python tech_info.py
      env:
        APP_ID: ${{ secrets.APP_ID }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
        OPEN_ID: ${{ secrets.OPEN_ID }}
        NEW_TEMPLATE_ID: ${{ secrets.NEW_TEMPLATE_ID }}
